// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwihxstdffgtqlmhbeps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3aWh4c3RkZmZndHFsbWhiZXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODA1NzAsImV4cCI6MjA2OTc1NjU3MH0.YFQilLkBL3RpBR1QtvykP_-DIoW4pw6yE3qkH1pIuzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});